services:
  postgresql:
    image: postgres:17-alpine
    container_name: habbit-postgres
    environment:
      POSTGRES_USER: habbit
      POSTGRES_PASSWORD: habbit
      POSTGRES_DB: habbit
    ports:
      - "5432:5432"
